src/main/routes/routes.py
from flask import render_template, url_for, request, redirect, Blueprint, send_file, session
import hashlib
import requests
import os
import random
from datetime import datetime, timedelta
from ..utils.rand_num_generators import gerar_numero_aleatorio, gerar_numero_aleatorio_img, gerar_numero_aleatorio_random, get_data
from ..utils.data_controllers import get_rows, get_all, check_victory, get_all_plants
from ..utils.json_data import load_user_access, save_user_access, today_str_func

main_bp = Blueprint("main_bp", __name__)
CACHE_DIR = 'cache'

last_sheet = ''
last_mode = 'normal'

used_values = [[],[],[],[],[]]
choosed_names = [[],[],[],[],[]]

victory = [False, False, False, False, False]
number_of_trys = [0,0,0,0,0]

infinity_number = 999

@main_bp.route("/")
@main_bp.route("/index")
def index():
    global rand, data, last_mode, last_sheet
    if last_sheet != 'Database':
        data, last_sheet = get_data('Database')
    if last_mode != 'normal':
        rand = gerar_numero_aleatorio('Database')
        last_mode = 'normal'

    names = data['Name'].tolist()
    today_str, yesterday_str = today_str_func()

    return render_template(
        "index.html",
        data = data,
        names = names,
        rows = get_rows(0,used_values, data, rand),
        used_values = used_values[0],
        choosed_names = choosed_names[0],
        rand = rand,
        victory = victory,
        number_of_trys = number_of_trys,
        user_access = load_user_access(),
        today = today_str,
        yesterday = yesterday_str
        )

@main_bp.route("/chinease")
def chinease():
    global rand, data, last_mode, last_sheet
    if last_sheet != 'Chinese_Database':
        rand = gerar_numero_aleatorio('Chinese_Database')
        data, last_sheet = get_data('Chinese_Database')
        last_mode = 'chinease'

    names = data['Name'].tolist()
    today_str, yesterday_str = today_str_func()

    return render_template(
        "chinease_version.html",
        data = data,
        names = names,
        rows = get_rows(1,used_values, data, rand),
        used_values = used_values[1],
        choosed_names = choosed_names[1],
        rand = rand,
        victory = victory,
        number_of_trys = number_of_trys,
        user_access = load_user_access(),
        today = today_str,
        yesterday = yesterday_str
        )

@main_bp.route("/all")
def all():
    global rand, data, last_mode, last_sheet
    if last_sheet != 'All_data':
        rand = gerar_numero_aleatorio('All_data')
        data, last_sheet = get_data('All_data')
        last_mode = 'all'

    names = data['Name'].tolist()
    today_str, yesterday_str = today_str_func()

    return render_template(
        "all_mode.html",
        data = data,
        names = names,
        rows = get_rows(2,used_values, data, rand),
        used_values = used_values[2],
        choosed_names = choosed_names[2],
        rand = rand,
        victory = victory,
        number_of_trys = number_of_trys,
        user_access = load_user_access(),
        today = today_str,
        yesterday = yesterday_str
        )

@main_bp.route("/img_guess")
def img_guess():
    global rand, data, last_mode, last_sheet
    if last_sheet != 'Database':
        data, last_sheet = get_data('Database')
    if last_mode != 'image':
        rand = gerar_numero_aleatorio_img('Database')
        last_mode = 'image'

    names = data['Name'].tolist()
    today_str, yesterday_str = today_str_func()

    return render_template(
        "image_guess.html",
        data = data,
        names = names,
        rows = get_rows(3,used_values, data, rand),
        used_values = used_values[3],
        choosed_names = choosed_names[3],
        used_values_len = len(used_values[3]),
        rand = rand,
        victory = victory,
        number_of_trys = number_of_trys,
        user_access = load_user_access(),
        today = today_str,
        yesterday = yesterday_str
        )

@main_bp.route("/infinity")
def infinity():
    global rand, data, infinity_number, last_mode, last_sheet
    if last_sheet != 'Database':
        data, last_sheet = get_data('Database')
        last_mode = 'infinity'
    if infinity_number == 999:
        rand = gerar_numero_aleatorio_random('Database')
        infinity_number = rand
    
    print(infinity_number)
    names = data['Name'].tolist()
    today_str, yesterday_str = today_str_func()
    return render_template(
        "infinity.html",
        data = data,
        names = names,
        rows = get_rows(9,used_values, data, rand),
        used_values = used_values[len(used_values)-1],
        choosed_names = choosed_names[len(choosed_names)-1],
        rand = rand,
        victory = victory[len(victory)-1],
        user_access = load_user_access(),
        today = today_str,
        yesterday = yesterday_str
        )

_cached_data = None
_last_sheet_loaded = None
_card_collection = []

@main_bp.route("/test")
def testes():
    global _cached_data, _last_sheet_loaded # Para simular o cache de dados globalmente neste exemplo

    if _last_sheet_loaded != 'Database' or _cached_data is None:
        _cached_data, _last_sheet_loaded = get_data('Database')

    sorted_cards_for_template = session.get('sorted_cards', []) 
    # Ao recuperar da sessão, converta a lista de volta para um set para manter a unicidade
    user_card_collection_list = session.get('user_card_collection', [])
    user_card_collection = set(user_card_collection_list)

    today_str, yesterday_str = today_str_func()
    
    return render_template(
        "test.html",
        data = _cached_data,
        rows = get_all_plants(_cached_data),
        user_access = load_user_access(),
        sorted_cards = sorted_cards_for_template, # As cartas sorteadas para exibir
        today = today_str,
        yesterday = yesterday_str,
        cards = user_card_collection
        )

@main_bp.route("/sortearcards")
def sortearcards():
    global _cached_data
    if _cached_data is None:
        _cached_data, _ = get_data('Database')

    sorted_cards = select_cards_by_rarity(get_all_plants(_cached_data))

    # 1. Recupera a coleção existente da sessão (ou cria uma nova lista vazia se não houver)
    # E converte para set para garantir a unicidade durante a adição
    user_card_collection_list = session.get('user_card_collection', [])
    user_card_collection_set = set(user_card_collection_list) # Convertido para set

    # 2. Adiciona os nomes das novas cartas à coleção usando .add() no set
    for card in sorted_cards:
        user_card_collection_set.add(card['name'])

    # 3. Armazena a coleção atualizada de volta na sessão, convertendo o set para list
    session['user_card_collection'] = list(user_card_collection_set) # Convertido de volta para list
    
    session['sorted_cards'] = sorted_cards
    return redirect(url_for('main_bp.testes'))

@main_bp.route("/test/<id>")
def testes_id(id):
    global data, last_sheet
    if last_sheet != 'Database':
        data, last_sheet = get_data('Database')

    plant = data.iloc[int(id)]

    return render_template(
        "test.html",
        data = data,
        plant = plant,
        )

@main_bp.route("/makeguess", methods=["GET","POST"])
def guesser():
    global victory, data
    
    id = int(request.form.get("id"))
    guess = request.form.get('guess')
    item = data[data['Name'].str.lower() == guess.lower()]

    used_values[id].append(int(item['ID'].iloc[0]))
    choosed_names[id].append(item['Name'].iloc[0])

    if data['Name'][rand-1] == item['Name'].iloc[0]:
        victory[id] = True
        number_of_trys[id] = used_values[id].__len__()

    info = load_user_access()
    today_str, yesterday_str = today_str_func()

    if check_victory(victory):
        values = {
            "last_acess": info["last_acess"],
            "daily_sequence": info['daily_sequence'],
            "total_victories": {
                "main": info['total_victories']["main"],
                "chinease": info['total_victories']["chinease"]+1,
                "crazy": info['total_victories']["crazy"]+1,
                "gnome": info['total_victories']["gnome"]+1
            }
        }
        save_user_access(values)
    elif victory[0] == True and info['last_acess'] != today_str:
        keep_sequence = info['daily_sequence']
        if info['last_acess'] == yesterday_str or info['last_acess'] == " ":
            keep_sequence = int(info['daily_sequence']) +1
        else:
            keep_sequence = 1
        values = {
            "last_acess": today_str,
            "daily_sequence": keep_sequence,
            "total_victories": {
                "main": info['total_victories']["main"]+1,
                "chinease": info['total_victories']["chinease"],
                "crazy": info['total_victories']["crazy"],
                "gnome": info['total_victories']["gnome"]
            }
        }
        save_user_access(values)

    if id == 0:
        return redirect(url_for('main_bp.index'))
    elif id ==1:
        return redirect(url_for('main_bp.chinease'))
    elif id ==2:
        return redirect(url_for('main_bp.all'))
    elif id ==3:
        return redirect(url_for('main_bp.img_guess'))
    else:
        return redirect(url_for('main_bp.infinity'))
   
@main_bp.route("/reset_infinity")
def reset_infinity():
    global rand
    rand = gerar_numero_aleatorio_random('Database')
    global victory
    used_values[len(victory)-1].clear()
    choosed_names[len(victory)-1].clear()
    victory[len(victory)-1] = False
    return redirect(url_for('main_bp.infinity'))

@main_bp.route("/proxy-image")
def proxy_image():
    # Substitua pelo link real da imagem
    image_url = request.args.get("img_link")  

    # Baixa a imagem ou retorna a versão do cache
    cached_image = download_image(image_url)

    # Retorna a imagem do cache
    return send_file(cached_image, mimetype='image/jpeg')

def get_cache_filename(url):

src/main/templates/all_mode.html
{% extends 'base.html' %}
{% block versao %}
Doidão
<span class="minimal">(Todas as plantas de todas as versões dos jogos!)</span>
{% endblock versao %}
{% block conteudo %}
<div class="container">
    <form action="/makeguess" class="form" method="post">
        <input type="hidden" name="id" value="2">
        <fieldset {% if victory[2] %} disabled {% endif %}>
        <div class="row align-items-center">
            <div class="col-auto">
                <label for="guess" class="form-label">Guess</label>
            </div>
            <div class="col">
                <!-- Associando o input ao datalist -->
                <input type="text" class="form-control" id="guess" name="guess" list="name-suggestions" aria-describedby="Guess" {% if victory[2] %} value="{{data['Name'][rand-1]}}" {% else %} autofocus {% endif %} oninput="validateInput()" required>
    
                <!-- Datalist contendo as sugestões -->
                <datalist id="name-suggestions">
                    {% for name in names %}
                        {% if name not in choosed_names %}
                            <option value="{{ name }}">
                        {% endif %}
                    {% endfor %}
                </datalist>
            </div>
            <div class="col-auto">
    
                <button type="submit" class="btn btn-guess">Make a guess</button>
    
            </div>
        </div>
        </fieldset>
    </form>
</div>
<div class="container">
    {% if victory[2] %}
    <div style="display: inline-flex; gap: 5px;">
        {% if number_of_trys[2] == 1 %}
            <span class="enfase">De primeira! </span>
        {% endif %}
        <span class="enfase">Você descobriu em {{ number_of_trys[2] }} tentativas!</span>
    </div>
    {% endif %}
    <div class="text-white">
        <div class="row">
            <div class="col">
                {% if victory[2] or used_values|length >= 5 %}
                <details>
                    <summary>Plant Food Effect</summary>
                    <p>{{ data['Plant Food Effect'][rand-1] | replace(data['Name'][rand-1], 'Esta planta') }}</p>
                </details>
                {% else %}
                    <p class="faded">Plant Food Effect após {{ 5 - used_values|length }} tentativas. </p>
                {% endif %}</div>
            <div class="col">
                {% if victory[2] or used_values|length >= 10 %}
                <details>
                    <summary>Description Effect</summary>
                    <p>{{ data['Description'][rand-1] | replace(data['Name'][rand-1], 'Esta planta') }}</p>
                </details>
                {% else %}
                    <p class="faded">Descrição após {{ 10 - used_values|length }} tentativas. </p>
                {% endif %}
            </div>
        </div>
    </div>
    {% if victory[0] == True and victory[1] == True and victory[2] == True %} 
        <div class="container whiteboard">
            <div class="area-results">
                <span class="victory">Victory!</span>
                <hr>
                <div class="victory-box">
                    <p>Você acertou todas as plantas!</p>
                    <p>Seu placar é de:</p>
                    <p>
                        <ul>
                            <li><span>PvZ Internacional:</span> <span>{{number_of_trys[0]}}</span></li>
                            <li><span>PvZ Chinease:</span> <span>{{number_of_trys[1]}}</span> | <span>PvZ Doidão:</span> <span>{{number_of_trys[2]}}</span></li>
                        </ul>
                    </p>
                </div>
                <br>
                <span class="enfase" style="color: var(--main-color);">Muito bem!</span>
            </div>
        </div>
    {% endif %}
</div>
<hr>

<div class="container c-table">
    <table class="table">
        <thead>
            <th><strong>Guess</strong></th>
            <th>Nome</th>
            <th>Família</th>
            <th>Custo de sóis</th>
            <th>Resistência</th>
            <th>Dano</th>
            <th>Recarga</th>
            <th>Uso</th>
            <th>Raridade</th>
            <th>Tipo de planta</th>
            <th>Origem</th>
            <th>Aparições</th>
        </thead>
        {% for row in rows %}
            <tr>
                <td class="{{ 'background-verde' if row.name == data['Name'][rand-1] else 'background-vermelho' }}"><img src="{{ url_for('main_bp.proxy_image', img_link=row.img_link) }}" alt="Imagem" class="img-plant"></td>
                <td class="{{ 'background-verde' if row.name == data['Name'][rand-1] else 'background-vermelho' }}">{{ row.name }}</td>
                <td class="{{ 'background-verde' if row.type == data['Type'][rand-1] else 'background-vermelho' }}">{{ row.type }}</td>
                <td class="{{ 'background-verde' if row.sun_cust == data['Sun Cust'][rand-1] else 'background-vermelho' }}">{{ row.sun_cust }}
                {% if row.sun_cust != data['Sun Cust'][rand-1] %}
                    {% if row.sun_cust > data['Sun Cust'][rand-1] %}
                        <ion-icon name="caret-down-circle-outline" class="icone"></ion-icon>
                    {% else %}
                        <ion-icon name="caret-up-circle-outline" class="icone"></ion-icon>
                    {% endif %}
                {% endif %}
                </td>
                <td class="{{ 'background-verde' if row.tought == data['Tought'][rand-1] else 'background-vermelho' }}">{{ row.tought }} 
                {% if row.tought != data['Tought'][rand-1] %}
                    {% if row.tought > data['Tought'][rand-1] %}
                        <ion-icon name="caret-down-circle-outline" class="icone"></ion-icon>
                    {% else %}
                        <ion-icon name="caret-up-circle-outline" class="icone"></ion-icon>
                    {% endif %}
                {% endif %}
                </td>
                <td class="{{ 'background-verde' if row.damage == data['Damage'][rand-1] else 'background-vermelho' }}">{{ row.damage }} 
                {% if row.damage != data['Damage'][rand-1] %}
                    {% if row.damage > data['Damage'][rand-1] %}
                        <ion-icon name="caret-down-circle-outline" class="icone"></ion-icon>
                    {% else %}
                        <ion-icon name="caret-up-circle-outline" class="icone"></ion-icon>
                    {% endif %}
                {% endif %}   
                </td>
                <td class="{{ 'background-verde' if row.recarga == data['Recarga'][rand-1] else 'background-vermelho' }}">{{ row.recarga }} 
                {% if row.recarga != data['Recarga'][rand-1] %}
                    {% if row.recarga > data['Recarga'][rand-1] %}
                        <ion-icon name="caret-down-circle-outline" class="icone"></ion-icon>
                    {% else %}
                        <ion-icon name="caret-up-circle-outline" class="icone"></ion-icon>
                    {% endif %}
                {% endif %}   
                </td>
                <td class="{% if row.usage[1]  %}
                            {% if row.usage[1] == data['Instant use'][rand-1] %}
                                background-verde
                            {% else %}
                                background-vermelho
                            {% endif %}
                        {% elif row.usage[0] %}
                            {% if row.usage[0] == data['Single use'][rand-1] and data['Instant use'][rand-1] == False%}
                                background-verde
                            {% else %}
                                background-vermelho
                            {% endif %}
                        {% else %}
                            {% if (False == data['Instant use'][rand-1] and False == data['Single use'][rand-1]) %}
                                background-verde
                            {% else %}
                                background-vermelho
                            {% endif %}
                        {% endif %}">
                    {% if row.usage[1] %}
                        Instant use
                    {% elif row.usage[0] %}
                        Single use
                    {% else %}
                        Continuos
                    {% endif %}
                    
                </td>
                <td class="{{ 'background-verde' if row.rarity == data['Rarity'][rand-1] else 'background-vermelho' }}">{{ row.rarity }}</td>
                <td class="{{ 'background-verde' if row.plant_origin == data['Plant_Origin'][rand-1] else 'background-vermelho' }}">{{ row.plant_origin }}</td>
                <td class="{{ 'background-verde' if row.origin == data['Origin'][rand-1] else 'background-vermelho' }}">{{ row.origin }}</td>
                <td class="{{ row.background }}">{{ row.appearances }}</td>               
            </tr>
        {% endfor %}
    </table>
</div>


<br>




<script>
    function validateInput() {
        var inputElement = document.getElementById('guess');
        var datalistOptions = document.getElementById('name-suggestions').options;
        var isValid = false;

        if (isValid){
            isValid = false
        }

        // Loop pelas opções do datalist
        for (var i = 0; i < datalistOptions.length; i++) {
            if (capitalize(inputElement.value) === capitalize(String(datalistOptions[i].value))) {
                isValid = true;
                break;
            }
        }

        // Se o valor não estiver na lista de opções, exibe uma mensagem de erro
        if (!isValid) {
            inputElement.setCustomValidity('Por favor, escolha um nome válido da lista.');
        } else {
            inputElement.setCustomValidity(''); // Se válido, limpa a mensagem de erro
        }
    }
    function capitalize(word){
        return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
    }
</script>
{% endblock %}

src/main/templates/chinease_version.html
{% extends 'base.html' %}
{% block versao %}
Chinesa
{% endblock versao %}
{% block conteudo %}
<div class="container">
    <form action="/makeguess" class="form" method="post">
        <input type="hidden" name="id" value="1">
        <fieldset {% if victory[1] %} disabled {% endif %}>
        <div class="row align-items-center">
            <div class="col-auto">
                <label for="guess" class="form-label">Guess</label>
            </div>
            <div class="col">
                <!-- Associando o input ao datalist -->
                <input type="text" class="form-control" id="guess" name="guess" list="name-suggestions" aria-describedby="Guess" {% if victory[1] %} value="{{data['Name'][rand-1]}}" {% else %} autofocus {% endif %} oninput="validateInput()" required>
    
                <!-- Datalist contendo as sugestões -->
                <datalist id="name-suggestions">
                    {% for name in names %}
                        {% if name not in choosed_names %}
                            <option value="{{ name }}">
                        {% endif %}
                    {% endfor %}
                </datalist>
            </div>
            <div class="col-auto">
    
                <button type="submit" class="btn btn-guess">Make a guess</button>
    
            </div>
        </div>
        </fieldset>
    </form>
</div>
<div class="container">
    {% if victory[1] %}
    <div style="display: inline-flex; gap: 5px;">
        {% if number_of_trys[1] == 1 %}
            <span class="enfase">De primeira! </span>
        {% endif %}
        <span class="enfase">Você descobriu em {{ number_of_trys[1] }} tentativas!</span>
    </div>
    {% endif %}
    <div class="text-white">
        <div class="row">
            <div class="col">
                {% if victory[1] or used_values|length >= 5 %}
                <details>
                    <summary>Plant Food Effect</summary>
                    <p>{{ data['Plant Food Effect'][rand-1] | replace(data['Name'][rand-1], 'Esta planta') }}</p>
                </details>
                {% else %}
                    <p class="faded">Plant Food Effect após {{ 5 - used_values|length }} tentativas. </p>
                {% endif %}</div>
            <div class="col">
                {% if victory[1] or used_values|length >= 10 %}
                <details>
                    <summary>Description Effect</summary>
                    <p>{{ data['Description'][rand-1] | replace(data['Name'][rand-1], 'Esta planta') }}</p>
                </details>
                {% else %}
                    <p class="faded">Descrição após {{ 10 - used_values|length }} tentativas. </p>
                {% endif %}
            </div>
        </div>
        
    </div>
    
    {% if victory[0] == True and victory[1] == True %} 
        <div class="container whiteboard">
            <div class="area-results">
                <span class="victory">Victory!</span>
                <hr>
                <div class="victory-box">
                    <p>Você acertou todas as plantas!</p>
                    <p>Seu placar é de:</p>
                    <p>
                        <ul>
                            <li><span>PvZ Internacional:</span> <span>{{number_of_trys[0]}}</span></li>
                            <li><span>PvZ Chinease:</span> <span>{{number_of_trys[1]}}</span></li>
                        </ul>
                    </p>
                </div>
                <br>
                <span class="enfase" style="color: var(--main-color);">Muito bem!</span>
            </div>
        </div>
    {% endif %}
</div>
<hr>

<div class="container c-table">
    <table class="table">
        <thead>
            <th><strong>Guess</strong></th>
            <th>Nome</th>
            <th>Família</th>
            <th>Custo de sóis</th>
            <th>Resistência</th>
            <th>Dano</th>
            <th>Recarga</th>
            <th>Uso</th>
            <th>Raridade</th>
            <th>Tipo de planta</th>
            <th>Origem</th>
            <th>Classificação</th>
            <th>Aparições</th>
        </thead>
        {% for row in rows %}
            <tr>
                <td class="{{ 'background-verde' if row.name == data['Name'][rand-1] else 'background-vermelho' }}"><img src="{{ url_for('main_bp.proxy_image', img_link=row.img_link) }}" alt="Imagem" class="img-plant"></td>
                <td class="{{ 'background-verde' if row.name == data['Name'][rand-1] else 'background-vermelho' }}">{{ row.name }}</td>
                <td class="{{ 'background-verde' if row.type == data['Type'][rand-1] else 'background-vermelho' }}">{{ row.type }}</td>
                <td class="{{ 'background-verde' if row.sun_cust == data['Sun Cust'][rand-1] else 'background-vermelho' }}">{{ row.sun_cust }}
                {% if row.sun_cust != data['Sun Cust'][rand-1] %}
                    {% if row.sun_cust > data['Sun Cust'][rand-1] %}
                        <ion-icon name="caret-down-circle-outline" class="icone"></ion-icon>
                    {% else %}
                        <ion-icon name="caret-up-circle-outline" class="icone"></ion-icon>
                    {% endif %}
                {% endif %}
                </td>
                <td class="{{ 'background-verde' if row.tought == data['Tought'][rand-1] else 'background-vermelho' }}">{{ row.tought }} 
                {% if row.tought != data['Tought'][rand-1] %}
                    {% if row.tought > data['Tought'][rand-1] %}
                        <ion-icon name="caret-down-circle-outline" class="icone"></ion-icon>
                    {% else %}
                        <ion-icon name="caret-up-circle-outline" class="icone"></ion-icon>
                    {% endif %}
                {% endif %}
                </td>
                <td class="{{ 'background-verde' if row.damage == data['Damage'][rand-1] else 'background-vermelho' }}">{{ row.damage }} 
                {% if row.damage != data['Damage'][rand-1] %}
                    {% if row.damage > data['Damage'][rand-1] %}
                        <ion-icon name="caret-down-circle-outline" class="icone"></ion-icon>
                    {% else %}
                        <ion-icon name="caret-up-circle-outline" class="icone"></ion-icon>
                    {% endif %}
                {% endif %}   
                </td>
                <td class="{{ 'background-verde' if row.recarga == data['Recarga'][rand-1] else 'background-vermelho' }}">{{ row.recarga }} 
                {% if row.recarga != data['Recarga'][rand-1] %}
                    {% if row.recarga > data['Recarga'][rand-1] %}
                        <ion-icon name="caret-down-circle-outline" class="icone"></ion-icon>
                    {% else %}
                        <ion-icon name="caret-up-circle-outline" class="icone"></ion-icon>
                    {% endif %}
                {% endif %}   
                </td>
                <td class="{% if row.usage[1]  %}
                            {% if row.usage[1] == data['Instant use'][rand-1] %}
                                background-verde
                            {% else %}
                                background-vermelho
                            {% endif %}
                        {% elif row.usage[0] %}
                            {% if row.usage[0] == data['Single use'][rand-1] and data['Instant use'][rand-1] == False%}
                                background-verde
                            {% else %}
                                background-vermelho
                            {% endif %}
                        {% else %}
                            {% if (False == data['Instant use'][rand-1] and False == data['Single use'][rand-1]) %}
                                background-verde
                            {% else %}
                                background-vermelho
                            {% endif %}
                        {% endif %}">
                    {% if row.usage[1] %}
                        Instant use
                    {% elif row.usage[0] %}
                        Single use
                    {% else %}
                        Continuos
                    {% endif %}
                    
                </td>
                <td class="{{ 'background-verde' if row.rarity == data['Rarity'][rand-1] else 'background-vermelho' }}">{{ row.rarity }}</td>
                <td class="{{ 'background-verde' if row.plant_origin == data['Plant_Origin'][rand-1] else 'background-vermelho' }}">{{ row.plant_origin }}</td>
                <td class="{{ 'background-verde' if row.origin == data['Origin'][rand-1] else 'background-vermelho' }}">{{ row.origin }}</td>
                <td class="{{ 'background-verde' if row.classification == data['Classification'][rand-1] else 'background-vermelho' }}">{{ row.classification }}</td>
                <td class="{{row.background}}">{{ row.appearances }}</td>               
            </tr>
        {% endfor %}
    </table>
</div>


<br>




<script>
    function validateInput() {
        var inputElement = document.getElementById('guess');
        var datalistOptions = document.getElementById('name-suggestions').options;
        var isValid = false;

        if (isValid){
            isValid = false
        }

        // Loop pelas opções do datalist
        for (var i = 0; i < datalistOptions.length; i++) {
            if (capitalize(inputElement.value) === capitalize(String(datalistOptions[i].value))) {
                isValid = true;
                break;
            }
        }

        // Se o valor não estiver na lista de opções, exibe uma mensagem de erro
        if (!isValid) {
            inputElement.setCustomValidity('Por favor, escolha um nome válido da lista.');
        } else {
            inputElement.setCustomValidity(''); // Se válido, limpa a mensagem de erro
        }
    }
    function capitalize(word){
        return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
    }
</script>
{% endblock %}